version: '3.8'
services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - REACT_APP_BASE_URL=http://localhost:8080/
    ports:
      - 3000:3000
    links:
      - backend